# Generated by Django 5.2 on 2025-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0002_starttest_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttest',
            name='current_question',
            field=models.IntegerField(default=-1),
        ),
    ]
