# Generated by Django 5.2 on 2025-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0005_alter_result_user_alter_result_user_not_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='starttest',
            name='question_finished',
            field=models.BooleanField(default=False),
        ),
    ]
