# Generated by Django 5.2 on 2025-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0006_starttest_question_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttest',
            name='users_not_auth',
            field=models.TextField(null=True),
        ),
    ]
