# Generated by Django 5.2 on 2025-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0007_alter_starttest_users_not_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttest',
            name='users_not_auth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
