# Generated by Django 5.2 on 2025-06-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTest', '0003_answerimage'),
        ('Tests', '0008_alter_starttest_users_not_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalresult',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateTest.test'),
        ),
        migrations.CreateModel(
            name='ResultNotAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('result', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTest.test')),
            ],
        ),
    ]
