# Generated by Django 5.2 on 2025-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mark',
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
    ]
