# Generated by Django 5.2 on 2025-06-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTest', '0003_answerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(null=True),
        ),
    ]
